### ISSUE TITLE
depricated rpc call `confirmTransaction` used

### ISSUE THREAD

**Issue by nuel77** [Block-Logic/ping-thing-client#25]
The code uses a deprecated rpc call `confirmTransaction` for waiting for tx confirmations, This call has been updated to `getSignatureStatus`

**Comment by WilfredAlmeida** [comment]
Hi @nuel77, the `confirmTransaction` RPC call is deprecated. The Ping Thing uses the `confirmTransaction` from the web3.js library with a confirmation strategy. This method doesn't use the deprecated RPC call, it subscribes to the tx signature and listens for confirmation.
